### ISSUE TITLE
https://karman-cms.herokuapp.com/ - 404

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [civictechro/apulum-admin#10]
https://karman-cms.herokuapp.com/ - 404

**Comment by ClaudiuCeia** [comment]
Hey there, just saw this, sorry. We've had this on hold for a while and will probably not touch it again until the summer. 

This is also in a very early development stage so it's not really something that you can reliably use - what were you interested in?

Anyway, the registration link is over at `https://karman-cms.herokuapp.com/register`. You'll receive an email to confirm your password which redirects you to the dashboard, but that's broken - a session won't be created and you need to actually login after confirming at `https://karman-cms.herokuapp.com/login`

Please let me know if you need further guidance!
